### ISSUE TITLE
Font not found

### ISSUE THREAD

**Issue by AriasAlan** [maycoon-ui/maycoon#34]
**Describe the bug**

I can't run any of the examples in the repository, they all give the same error:

```
thread 'main' panicked at maycoon-core/src/app/font_ctx.rs:57:14:
Failed to select default font: NotFound
```

```
[jor@endeavour hello_world]$ RUST_BACKTRACE=1 cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `/home/jor/rust/gittest/maycoon/target/debug/hello_world`
thread 'main' panicked at maycoon-core/src/app/font_ctx.rs:57:14:
Failed to select default font: NotFound
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::expect
             at /home/jor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1061:23
   4: <maycoon_core::app::font_ctx::FontContext as core::default::Default>::default
             at /home/jor/rust/gittest/maycoon/maycoon-core/src/app/font_ctx.rs:55:28
   5: maycoon_core::app::MayApp<T>::new
             at /home/jor/rust/gittest/maycoon/maycoon-core/src/app/mod.rs:48:23
   6: hello_world::main
             at ./src/main.rs:10:5
   7: core::ops::function::FnOnce::call_once
             at /home/jor/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```

**Platform:**
 - OS: EndeavourOS
 - DE: LXDE
 - WM: Openbox (x11)
 - Cargo Version: 1.83.0 (5ffbef321 2024-10-29)
 - Crate Version: current version (I guess)

**Additional context**

I also tried the same on another pc with debian and it gave a similar error

**Comment by DraftedDev** [comment]
Thanks. Must be the default font selection, that requires the default font (`ArialMT`) to be installed on the OS. Looking into it...

**Comment by DraftedDev** [comment]
Fixed with commit https://github.com/maycoon-ui/maycoon/commit/862493cff7460cccb769e9f47495a8f07f9423e3

**Comment by djmitche** [comment]
I'm still seeing this error on 0.3.0, which includes that fix, while trying to run the example. I've tried with all combinations of features `vg` and `include-noto-sans` with the same result. I mostly just want to see what this UI looks like, so running the example is the first step in evaluating it -- it would be great if that "just worked" :)

**Comment by DraftedDev** [comment]
> I'm still seeing this error on 0.3.0, which includes that fix, while trying to run the example. I've tried with all combinations of features `vg` and `include-noto-sans` with the same result. I mostly just want to see what this UI looks like, so running the example is the first step in evaluating it -- it would be great if that "just worked" :)

I've been having some trouble with cargo `release-plz` publishing errors, so I quickly re-worked the default font selection system.
I tried to make it as cross-platform as possible. On linux, the "NotoSans" font is selected by default. Otherwise the "ArialMT" font is selected. Thanks for bringing this to my attention. I had doubts about my temporary solution.

**Comment by DraftedDev** [comment]
Hopefully fixed with https://github.com/maycoon-ui/maycoon/commit/0d49d4cdaee63a9233175c4500881453c833cbf5.
I looked into how `bevy` manages its default fonts and the Noto Sans font is now inside the "src" directory of the `maycoon-core` crate. The examples should work on (hopefully) most desktop systems now.

**Comment by djmitche** [comment]
Hm, I'm still getting the same error, now with 0.3.2.

```
[package]
name = "mcplay"
version = "0.1.0"
edition = "2024"

[dependencies]
maycoon = { version = "0.3.2", features = ["include-noto-sans"] }
```

`src/main.rs` is copied directly from https://maycoon-ui.github.io/guide/qick-start/basic-app.html.

```
thread 'main' panicked at /home/dustin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/maycoon-core-0.3.2/src/app/font_ctx.rs:80:26:
Failed to select default font: NotFound
```

I'm using Ubuntu 24.04, with Rust 1.86.0.

**Comment by DraftedDev** [comment]
> Hm, I'm still getting the same error, now with 0.3.2.
> 
> ```
> [package]
> name = "mcplay"
> version = "0.1.0"
> edition = "2024"
> 
> [dependencies]
> maycoon = { version = "0.3.2", features = ["include-noto-sans"] }
> ```
> 
> `src/main.rs` is copied directly from https://maycoon-ui.github.io/guide/qick-start/basic-app.html.
> 
> ```
> thread 'main' panicked at /home/dustin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/maycoon-core-0.3.2/src/app/font_ctx.rs:80:26:
> Failed to select default font: NotFound
> ```
> 
> I'm using Ubuntu 24.04, with Rust 1.86.0.

Don't use the new version. It doesn't have the fix yet. Please use this git repository and try again.

**Comment by djmitche** [comment]
Ah, sorry, I misread the GitHub tags in the linked commit. Using the latest in the git repository works fine! Thanks!

**Comment by DraftedDev** [comment]
Thanks for the feedback. Closing this as complete!
